- name: DEPLOY AS3
  hosts: localhost
  connection: localhost
  gather_facts: no 

  vars_files:
   - ../creds/big_creds.yaml

  vars:
    uri_method: POST

  tasks:
    - name: declaration
      uri:
        url: https://18.197.132.221/mgmt/shared/appsvcs/declare
        method: "{{ uri_method }}"
        user: "{{ bigip_user }}"
        password: "{{ bigip_pass }}"
        body: "{{ lookup('file','simple-as3.json') }}"
        force_basic_auth: yes
        body_format: json
        validate_certs: no
        status_code: 200
        body_format: json
